### ISSUE TITLE
kismet-ubertooth double frees in ubertooth::poll

### ISSUE THREAD

**Issue by ikelos** [greatscottgadgets/ubertooth#59]
Hi there,

Everytime I run kismet_server -c ubertooth, the ubertooth::poll method seems to cause a double free at line 508 in packetsource_ubertooth.cc after it receives its second packet (this happens even if the two LAPs are not the same).  I'm using libbtbb, ubertooth, kismet and kismet-ubertooth all from git, this also happens with non-git versions of the software as well (ubertooth 2014.04.1 and kismet 2013.03.1).  Tested with original/purchase firmware and 2014-04-R1 firmware.

I'm happy to provide any further diagnostics that might help narrow down the issue.  Just let me know what you need.  5:)

```
INFO: Started source 'ubertooth'
rx blocks of 64 bytes in 512 byte transfers
INFO: kismet_capture pid 21183 synced with Kismet server, starting service 
      loop
GOT PACKET ch=49 LAP=1928c7 err=0 clk100ns=235484
GOT PACKET ch=19 LAP=1928c7 err=0 clk100ns=235757
INFO: Detected new Bluetooth baseband device 00:00:00:19:28:C7
*** Error in `/usr/bin/kismet_server': double free or corruption (out): 0x00007fffec000ac0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x730db)[0x7ffff67b70db]
/lib64/libc.so.6(+0x785ce)[0x7ffff67bc5ce]
/lib64/libc.so.6(+0x78dbb)[0x7ffff67bcdbb]
/usr/lib64/kismet/ubertooth.so(_ZN22PacketSource_Ubertooth4PollEv+0xab)[0x7ffff58a70fb]
/usr/bin/kismet_server(_ZN19Packetsourcetracker4PollER6fd_setS1_+0x31a)[0x468f7a]
/usr/bin/kismet_server(main+0x17ed)[0x42e99d]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7ffff6763fa0]
/usr/bin/kismet_server[0x42faa0]
======= Memory map: ========
00400000-005aa000 r-xp 00000000 08:02 6861207                            /usr/bin/kismet_server
007a9000-007aa000 r--p 001a9000 08:02 6861207                            /usr/bin/kismet_server
007aa000-007ad000 rw-p 001aa000 08:02 6861207                            /usr/bin/kismet_server
007ad000-00817000 rw-p 00000000 00:00 0                                  [heap]
7fffec000000-7fffec021000 rw-p 00000000 00:00 0 
7fffec021000-7ffff0000000 ---p 00000000 00:00 0 
7ffff2914000-7ffff2915000 ---p 00000000 00:00 0 
7ffff2915000-7ffff3115000 rw-p 00000000 00:00 0                          [stack:21185]
7ffff3115000-7ffff3116000 ---p 00000000 00:00 0 
7ffff3116000-7ffff3916000 rw-p 00000000 00:00 0                          [stack:21184]
7ffff3916000-7ffff392b000 r-xp 00000000 08:02 3020476                    /lib64/libz.so.1.2.8
7ffff392b000-7ffff3b2a000 ---p 00015000 08:02 3020476                    /lib64/libz.so.1.2.8
7ffff3b2a000-7ffff3b2b000 r--p 00014000 08:02 3020476                    /lib64/libz.so.1.2.8
7ffff3b2b000-7ffff3b2c000 rw-p 00015000 08:02 3020476                    /lib64/libz.so.1.2.8
7ffff3b2c000-7ffff3d37000 r-xp 00000000 08:02 6828741                    /usr/lib64/libcrypto.so.1.0.0
7ffff3d37000-7ffff3f36000 ---p 0020b000 08:02 6828741                    /usr/lib64/libcrypto.so.1.0.0
7ffff3f36000-7ffff3f52000 r--p 0020a000 08:02 6828741                    /usr/lib64/libcrypto.so.1.0.0
7ffff3f52000-7ffff3f5e000 rw-p 00226000 08:02 6828741                    /usr/lib64/libcrypto.so.1.0.0
7ffff3f5e000-7ffff3f61000 rw-p 00000000 00:00 0 
7ffff3f61000-7ffff3f74000 r-xp 00000000 08:02 7347906                    /usr/lib64/kismet/aircrack-kismet.so
7ffff3f74000-7ffff4173000 ---p 00013000 08:02 7347906                    /usr/lib64/kismet/aircrack-kismet.so
7ffff4173000-7ffff4174000 r--p 00012000 08:02 7347906                    /usr/lib64/kismet/aircrack-kismet.so
7ffff4174000-7ffff4175000 rw-p 00013000 08:02 7347906                    /usr/lib64/kismet/aircrack-kismet.so
7ffff4175000-7ffff4183000 rw-p 00000000 00:00 0 
7ffff4183000-7ffff418f000 r-xp 00000000 08:02 7348388                    /usr/lib64/kismet/spectool_net.so
7ffff418f000-7ffff438f000 ---p 0000c000 08:02 7348388                    /usr/lib64/kismet/spectool_net.so
7ffff438f000-7ffff4390000 r--p 0000c000 08:02 7348388                    /usr/lib64/kismet/spectool_net.so
7ffff4390000-7ffff4391000 rw-p 0000d000 08:02 7348388                    /usr/lib64/kismet/spectool_net.so
7ffff4391000-7ffff4396000 r-xp 00000000 08:02 7348389                    /usr/lib64/kismet/kismet-syslog.so
7ffff4396000-7ffff4596000 ---p 00005000 08:02 7348389                    /usr/lib64/kismet/kismet-syslog.so
7ffff4596000-7ffff4597000 r--p 00005000 08:02 7348389                    /usr/lib64/kismet/kismet-syslog.so
7ffff4597000-7ffff4598000 rw-p 00006000 08:02 7348389                    /usr/lib64/kismet/kismet-syslog.so
7ffff4598000-7ffff45b6000 r-xp 00000000 08:02 6849727                    /usr/lib64/libbluetooth.so.3.18.1
7ffff45b6000-7ffff47b5000 ---p 0001e000 08:02 6849727                    /usr/lib64/libbluetooth.so.3.18.1
7ffff47b5000-7ffff47b6000 r--p 0001d000 08:02 6849727                    /usr/lib64/libbluetooth.so.3.18.1
7ffff47b6000-7ffff47b9000 rw-p 0001e000 08:02 6849727                    /usr/lib64/libbluetooth.so.3.18.1
7ffff47b9000-7ffff47cc000 r-xp 00000000 08:02 7348217                    /usr/lib64/kismet/btscan.so
7ffff47cc000-7ffff49cc000 ---p 00013000 08:02 7348217                    /usr/lib64/kismet/btscan.so
7ffff49cc000-7ffff49cd000 r--p 00013000 08:02 7348217                    /usr/lib64/kismet/btscan.so
7ffff49cd000-7ffff49ce000 rw-p 00014000 08:02 7348217                    /usr/lib64/kismet/btscan.so
7ffff49ce000-7ffff49d5000 r-xp 00000000 08:02 7347951                    /usr/lib64/kismet/autowep-kismet.so
7ffff49d5000-7ffff4bd4000 ---p 00007000 08:02 7347951                    /usr/lib64/kismet/autowep-kismet.so
7ffff4bd4000-7ffff4bd5000 r--p 00006000 08:02 7347951                    /usr/lib64/kismet/autowep-kismet.so
7ffff4bd5000-7ffff4bd6000 rw-p 00007000 08:02 7347951                    /usr/lib64/kismet/autowep-kismet.so
7ffff4bd6000-7ffff4bda000 r-xp 00000000 08:02 3018580                    /lib64/libattr.so.1.1.0
7ffff4bda000-7ffff4dd9000 ---p 00004000 08:02 3018580                    /lib64/libattr.so.1.1.0
7ffff4dd9000-7ffff4dda000 r--p 00003000 08:02 3018580                    /lib64/libattr.so.1.1.0
7ffff4dda000-7ffff4ddb000 rw-p 00004000 08:02 3018580                    /lib64/libattr.so.1.1.0
7ffff4ddb000-7ffff4ddf000 r-xp 00000000 08:02 3020480                    /lib64/libcap.so.2.22
7ffff4ddf000-7ffff4fdf000 ---p 00004000 08:02 3020480                    /lib64/libcap.so.2.22
7ffff4fdf000-7ffff4fe0000 r--p 00004000 08:02 3020480                    /lib64/libcap.so.2.22
7ffff4fe0000-7ffff4fe1000 rw-p 00005000 08:02 3020480                    /lib64/libcap.so.2.22
7ffff4fe1000-7ffff4fe8000 r-xp 00000000 08:02 3018827                    /lib64/librt-2.20.so
7ffff4fe8000-7ffff51e7000 ---p 00007000 08:02 3018827                    /lib64/librt-2.20.so
7ffff51e7000-7ffff51e8000 r--p 00006000 08:02 3018827                    /lib64/librt-2.20.so
7ffff51e8000-7ffff51e9000 rw-p 00007000 08:02 3018827                    /lib64/librt-2.20.so
7ffff51e9000-7ffff51f1000 r-xp 00000000 08:02 6844907                    /usr/lib64/libubertooth.so.0.2
7ffff51f1000-7ffff53f1000 ---p 00008000 08:02 6844907                    /usr/lib64/libubertooth.so.0.2
7ffff53f1000-7ffff53f2000 r--p 00008000 08:02 6844907                    /usr/lib64/libubertooth.so.0.2
7ffff53f2000-7ffff53f3000 rw-p 00009000 08:02 6844907                    /usr/lib64/libubertooth.so.0.2
7ffff53f3000-7ffff53f4000 rw-p 00000000 00:00 0 
7ffff53f4000-7ffff5404000 r-xp 00000000 08:02 6862312                    /usr/lib64/libbtbb.so.0.3
7ffff5404000-7ffff5603000 ---p 00010000 08:02 6862312                    /usr/lib64/libbtbb.so.0.3
7ffff5603000-7ffff5604000 r--p 0000f000 08:02 6862312                    /usr/lib64/libbtbb.so.0.3
7ffff5604000-7ffff5605000 rw-p 00010000 08:02 6862312                    /usr/lib64/libbtbb.so.0.3
7ffff5605000-7ffff5685000 rw-p 00000000 00:00 0 
7ffff5685000-7ffff569b000 r-xp 00000000 08:02 3020863                    /lib64/libusb-1.0.so.0.1.0
7ffff569b000-7ffff589b000 ---p 00016000 08:02 3020863                    /lib64/libusb-1.0.so.0.1.0
7ffff589b000-7ffff589c000 r--p 00016000 08:02 3020863                    /lib64/libusb-1.0.so.0.1.0
7ffff589c000-7ffff589d000 rw-p 00017000 08:02 3020863                    /lib64/libusb-1.0.so.0.1.0
7ffff589d000-7ffff58b1000 r-xp 00000000 08:02 7348216                    /usr/lib64/kismet/ubertooth.so
7ffff58b1000-7ffff5ab1000 ---p 00014000 08:02 7348216                    /usr/lib64/kismet/ubertooth.so
7ffff5ab1000-7ffff5ab2000 r--p 00014000 08:02 7348216                    /usr/lib64/kismet/ubertooth.so
7ffff5ab2000-7ffff5ab3000 rw-p 00015000 08:02 7348216                    /usr/lib64/kismet/ubertooth.so
7ffff5ab3000-7ffff5abe000 r-xp 00000000 08:02 3018834                    /lib64/libnss_files-2.20.so
7ffff5abe000-7ffff5cbd000 ---p 0000b000 08:02 3018834                    /lib64/libnss_files-2.20.so
7ffff5cbd000-7ffff5cbe000 r--p 0000a000 08:02 3018834                    /lib64/libnss_files-2.20.so
7ffff5cbe000-7ffff5cbf000 rw-p 0000b000 08:02 3018834                    /lib64/libnss_files-2.20.so
7ffff5cbf000-7ffff5cc9000 r-xp 00000000 08:02 3018835                    /lib64/libnss_nis-2.20.so
7ffff5cc9000-7ffff5ec8000 ---p 0000a000 08:02 3018835                    /lib64/libnss_nis-2.20.so
7ffff5ec8000-7ffff5ec9000 r--p 00009000 08:02 3018835                    /lib64/libnss_nis-2.20.so
7ffff5ec9000-7ffff5eca000 rw-p 0000a000 08:02 3018835                    /lib64/libnss_nis-2.20.so
7ffff5eca000-7ffff5edf000 r-xp 00000000 08:02 3018840                    /lib64/libnsl-2.20.so
7ffff5edf000-7ffff60de000 ---p 00015000 08:02 3018840                    /lib64/libnsl-2.20.so
7ffff60de000-7ffff60df000 r--p 00014000 08:02 3018840                    /lib64/libnsl-2.20.so
7ffff60df000-7ffff60e0000 rw-p 00015000 08:02 3018840                    /lib64/libnsl-2.20.so
7ffff60e0000-7ffff60e2000 rw-p 00000000 00:00 0 
7ffff60e2000-7ffff60e9000 r-xp 00000000 08:02 3018838                    /lib64/libnss_compat-2.20.so
7ffff60e9000-7ffff62e8000 ---p 00007000 08:02 3018838                    /lib64/libnss_compat-2.20.so
7ffff62e8000-7ffff62e9000 r--p 00006000 08:02 3018838                    /lib64/libnss_compat-2.20.so
7ffff62e9000-7ffff62ea000 rw-p 00007000 08:02 3018838                    /lib64/libnss_compat-2.20.so
7ffff62ea000-7ffff6328000 r-xp 00000000 08:02 6816765                    /usr/lib64/libdbus-1.so.3.8.11
7ffff6328000-7ffff6527000 ---p 0003e000 08:02 6816765                    /usr/lib64/libdbus-1.so.3.8.11
7ffff6527000-7ffff6528000 r--p 0003d000 08:02 6816765                    /usr/lib64/libdbus-1.so.3.8.11
7ffff6528000-7ffff6529000 rw-p 0003e000 08:02 6816765                    /usr/lib64/libdbus-1.so.3.8.11
7ffff6529000-7ffff653f000 r-xp 00000000 08:02 3018824                    /lib64/libpthread-2.20.so
7ffff653f000-7ffff673e000 ---p 00016000 08:02 3018824                    /lib64/libpthread-2.20.so
7ffff673e000-7ffff673f000 r--p 00015000 08:02 3018824                    /lib64/libpthread-2.20.so
7ffff673f000-7ffff6740000 rw-p 00016000 08:02 3018824                    /lib64/libpthread-2.20.so
7ffff6740000-7ffff6744000 rw-p 00000000 00:00 0 
7ffff6744000-7ffff68d7000 r-xp 00000000 08:02 3018887                    /lib64/libc-2.20.so
7ffff68d7000-7ffff6ad7000 ---p 00193000 08:02 3018887                    /lib64/libc-2.20.so
7ffff6ad7000-7ffff6adb000 r--p 00193000 08:02 3018887                    /lib64/libc-2.20.so
7ffff6adb000-7ffff6add000 rw-p 00197000 08:02 3018887                    /lib64/libc-2.20.so
7ffff6add000-7ffff6ae1000 rw-p 00000000 00:00 0 
7ffff6ae1000-7ffff6af6000 r-xp 00000000 08:02 1322882                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libgcc_s.so.1
7ffff6af6000-7ffff6cf6000 ---p 00015000 08:02 1322882                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libgcc_s.so.1
7ffff6cf6000-7ffff6cf7000 r--p 00015000 08:02 1322882                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libgcc_s.so.1
7ffff6cf7000-7ffff6cf8000 rw-p 00016000 08:02 1322882                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libgcc_s.so.1
7ffff6cf8000-7ffff6df2000 r-xp 00000000 08:02 3018795                    /lib64/libm-2.20.so
7ffff6df2000-7ffff6ff1000 ---p 000fa000 08:02 3018795                    /lib64/libm-2.20.so
7ffff6ff1000-7ffff6ff2000 r--p 000f9000 08:02 3018795                    /lib64/libm-2.20.so
7ffff6ff2000-7ffff6ff3000 rw-p 000fa000 08:02 3018795                    /lib64/libm-2.20.so
7ffff6ff3000-7ffff700f000 r-xp 00000000 08:02 6838916                    /usr/lib64/libnl-3.so.200.20.0
7ffff700f000-7ffff720f000 ---p 0001c000 08:02 6838916                    /usr/lib64/libnl-3.so.200.20.0
7ffff720f000-7ffff7211000 r--p 0001c000 08:02 6838916                    /usr/lib64/libnl-3.so.200.20.0
7ffff7211000-7ffff7212000 rw-p 0001e000 08:02 6838916                    /usr/lib64/libnl-3.so.200.20.0
7ffff7212000-7ffff7217000 r-xp 00000000 08:02 6874333                    /usr/lib64/libnl-genl-3.so.200.20.0
7ffff7217000-7ffff7416000 ---p 00005000 08:02 6874333                    /usr/lib64/libnl-genl-3.so.200.20.0
7ffff7416000-7ffff7417000 r--p 00004000 08:02 6874333                    /usr/lib64/libnl-genl-3.so.200.20.0
7ffff7417000-7ffff7418000 rw-p 00005000 08:02 6874333                    /usr/lib64/libnl-genl-3.so.200.20.0
7ffff7418000-7ffff7457000 r-xp 00000000 08:02 6850347                    /usr/lib64/libpcap.so.1.6.2
7ffff7457000-7ffff7657000 ---p 0003f000 08:02 6850347                    /usr/lib64/libpcap.so.1.6.2
7ffff7657000-7ffff7659000 r--p 0003f000 08:02 6850347                    /usr/lib64/libpcap.so.1.6.2
7ffff7659000-7ffff765a000 rw-p 00041000 08:02 6850347                    /usr/lib64/libpcap.so.1.6.2
7ffff765a000-7ffff765b000 rw-p 00000000 00:00 0 
7ffff765b000-7ffff774c000 r-xp 00000000 08:02 1322925                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libstdc++.so.6.0.20
7ffff774c000-7ffff794c000 ---p 000f1000 08:02 1322925                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libstdc++.so.6.0.20
7ffff794c000-7ffff7954000 r--p 000f1000 08:02 1322925                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libstdc++.so.6.0.20
7ffff7954000-7ffff7956000 rw-p 000f9000 08:02 1322925                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.2/libstdc++.so.6.0.20
7ffff7956000-7ffff796b000 rw-p 00000000 00:00 0 
7ffff796b000-7ffff79d5000 r-xp 00000000 08:02 3014709                    /lib64/libpcre.so.1.2.4
7ffff79d5000-7ffff7bd5000 ---p 0006a000 08:02 3014709                    /lib64/libpcre.so.1.2.4
7ffff7bd5000-7ffff7bd6000 r--p 0006a000 08:02 3014709                    /lib64/libpcre.so.1.2.4
7ffff7bd6000-7ffff7bd7000 rw-p 0006b000 08:02 3014709                    /lib64/libpcre.so.1.2.4
7ffff7bd7000-7ffff7bd9000 r-xp 00000000 08:02 3018802                    /lib64/libdl-2.20.so
7ffff7bd9000-7ffff7dd9000 ---p 00002000 08:02 3018802                    /lib64/libdl-2.20.so
7ffff7dd9000-7ffff7dda000 r--p 00002000 08:02 3018802                    /lib64/libdl-2.20.so
7ffff7dda000-7ffff7ddb000 rw-p 00003000 08:02 3018802                    /lib64/libdl-2.20.so
7ffff7ddb000-7ffff7dfd000 r-xp 00000000 08:02 3018886                    /lib64/ld-2.20.so
7ffff7f43000-7ffff7fb3000 rw-p 00000000 00:00 0 
7ffff7fdb000-7ffff7fe0000 rw-p 00000000 00:00 0 
7ffff7fe0000-7ffff7ff4000 r-xp 00000000 08:02 6869250                    /usr/lib64/libudev.so.1.6.2
7ffff7ff4000-7ffff7ff5000 r--p 00013000 08:02 6869250                    /usr/lib64/libudev.so.1.6.2
7ffff7ff5000-7ffff7ff6000 rw-p 00014000 08:02 6869250                    /usr/lib64/libudev.so.1.6.2
7ffff7ff6000-7ffff7ff8000 rw-p 00000000 00:00 0 
7ffff7ff8000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00021000 08:02 3018886                    /lib64/ld-2.20.so
7ffff7ffd000-7ffff7ffe000 rw-p 00022000 08:02 3018886                    /lib64/ld-2.20.so
7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0 
7ffffffdd000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Program received signal SIGABRT, Aborted.
0x00007ffff6777a27 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) bt full
#0  0x00007ffff6777a27 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 21179
        selftid = 21179
#1  0x00007ffff6778dba in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x64765b2020202020, sa_sigaction = 0x64765b2020202020}, sa_mask = {__val = {7378697426076266355, 3472328516180522854, 7365468305578407725, 
              3274715270390768742, 3544948840217997357, 3475151841819373616, 4051049648732971058, 2314885530818453558, 2314885530818453536, 7596498486491619360, 3615656491659572834, 3966104962339975726, 
              7234582239544501862, 7378697426660503600, 3472328524770457446, 0}}, sa_flags = 95, sa_restorer = 0x7fffffffcd70}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff67b70e0 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff68ab438 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 0, overflow_arg_area = 0x7fffffffcd80, reg_save_area = 0x7fffffffcd10}}
        fd = 11
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007ffff67bc5ce in malloc_printerr (action=3, str=0x7ffff68ab590 "double free or corruption (out)", ptr=<optimized out>) at malloc.c:4958
        buf = "00007fffec000ac0"
        cp = <optimized out>
#4  0x00007ffff67bcdbb in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3829
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
        __func__ = "_int_free"
#5  0x00007ffff58a70fb in PacketSource_Ubertooth::Poll (this=0x7ffff7f43010) at packetsource_ubertooth.cc:508
        newpack = 0x7bb570
        pkt = 0x7fffec000ac0
        rawchunk = 0x7dcd50
        x = 0
        rx = 98 'b'
        read_size = <optimized out>
        process_packet = <optimized out>
#6  0x0000000000468f7a in Packetsourcetracker::Poll (this=0x7b9180, in_rset=..., in_wset=...) at packetsourcetracker.cc:629
        capd = 27
        x = {first = 1, second = }
#7  0x000000000042e99d in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at kismet_server.cc:1327
        x = 2
        startroot = <optimized out>
        rset = {fds_bits = {134217728, 0 <repeats 15 times>}}
        wset = {fds_bits = {0 <repeats 16 times>}}
        nlwc = <optimized out>
        hdwc = <optimized out>
        chantracker = <optimized out>
        configfilename = <optimized out>
        option_idx = 0
        startup_ipc_id = 6
...
```

**Comment by dominicgs** [comment]
Thank you for the detailed report - the issue appears to be similar to, if not the same as, issue #18.  I'll leave this issue open until I've verified that it's the same or fixed them both.

The fact that it happens after two packets is interesting.  Is that reliably after the second packet each time?

**Comment by ikelos** [comment]
Yep, whether the LAP is the same for the two packets or not, I haven't had an occasion where the crash hasn't happened after the second packet.

**Comment by ohyeahq** [comment]
The same here.

Antergos latest rolling; others latest stable

Any workaround or quick hack please?

I know double free is notoriously hard to fix, especially in C++; we often have to put null in the pointer explicitly on initialization and right after freeing; we often have to write our own copy constructor and operator = (instead of relying on the auto-generated ones).  

I'm in a hurry and I just commented out line 508.  Leaky, yes, very bad, but working (for now).  

Cheeeeers

**Comment by dominicgs** [comment]
I have now merged pull request #193 that should fix this issue.

**Comment by ohyeahq** [comment]
Thanks so much for your effort.  I truly appreciate it.  The git clone works fine for me now for this issue.  A bad news is that the 14-bytes issue (#92) is still there.  I'll leave a report on #92.

**Comment by dominicgs** [comment]
@ohyeahq #92 is at the top of my todo list and will be completed as soon as possible.

I'm going to close this issue as fixed.
